version: '3'
services:
    database:
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        image: mariadb:10
        networks:
            - backend
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql
    php:
        build: ./php-fpm
        depends_on:
            - database
        links:
            - database
        networks:
            - backend
            - frontend
        expose: 
            - "9000"
        volumes:
            - ./symfony:/var/www
            - ./logs/symfony:/var/www/var/log
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
    nginx:
        build: ./nginx
        restart: always
        depends_on:
            - php
            - database
        links:
            - database
            - php
        networks:
            - frontend
        ports:
            - "80:80"
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./symfony:/var/www

networks:
    frontend:
    backend:
